name: PhysicalShop
main: com.wolvereness.physicalshop.PhysicalShop
version: 9.0.15
softdepend: [LogBlock, LWC, Lockette]
url: http://dev.bukkit.org/server-mods/physicalshop/
commands:
   physicalshop:
      description: Reloads the configuration
authors:
    - Wolvereness